### PR TITLE
modularize the program

### PR DESCRIPTION
**Pull request by johncoleman83**
I've begun to modularize your program.  If you want this to scale, you cannot have everything in 1 script.

Eventually you should build methods to  handle all the repeated code you have as well.

CC: @cherryWood55

### CODE REVIEW

**Comment by johncoleman83** [comment]
@cherryWood55, do you want me to fix merge conflicts, or do you not want to modularize your program?

**Comment by cherryWood55** [comment]
Can you fix merge conflicts?

**Comment by johncoleman83** [comment]
@cherryWood55 , fixed

**Comment by cherryWood55** [comment]
> 
> 
> @cherryWood55 , fixed

Thanks!

**Pull request merged**
