### PR TITLE
"Add more questions #1" - Added a new topic

### PR DESCRIPTION
**Pull request by prem1835**
I added a new topic worldgk.py and made some necessary changes.
with 5 questions in this new topic

### CODE REVIEW

**Comment by cherryWood55** [comment]
I am getting a conflict issue, @prem1835 . Please check your code again. Thanks!

**Comment by prem1835** [comment]
I resolved the conflicts. please check it

**Comment by cherryWood55** [comment]
I will. Thanks!

**Comment by cherryWood55** [comment]
Great job @prem1835 ! I saw your commits. Unfortunately, the conflict error still persists as a result of which I am unable to merge your PR. Would you mind seeing the project and adding your files then? Thanks a lot.

**Comment by prem1835** [comment]
Ok , I will checkout

**Comment by prem1835** [comment]
I already created a new pr so I am closing it

**Pull request closed without merging**
